services:
    app.helper.city_catalog_helper:
        class:  App\Helper\CityCatalogHelper
        arguments: ['@doctrine.orm.entity_manager', '@security.encoder_factory', '@app.sender.registration', '@app.generator.password_generator']
        public: true

    app.helper.article_comment:
        class:  App\Helper\ArticleCommentHelper
        arguments: []
        public: true