services:
    App\Twig\ShowCodeExtension:
        class: App\Twig\ShowCodeExtension
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: twig.extension }

    App\Twig\DefaultImageExtension:
        class: App\Twig\DefaultImageExtension
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: twig.extension }

    App\Twig\DefaultTextExtension:
        class: App\Twig\DefaultTextExtension
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: twig.extension }

    App\Twig\NotFoundPageDataExtension:
        class: App\Twig\NotFoundPageDataExtension
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: twig.extension }

    App\Twig\TitleTransformerExtension:
        class: App\Twig\TitleTransformerExtension
        arguments: ['@app.provider.title_provider']
        tags:
            - { name: twig.extension }

    App\Twig\ObjectProviderExtension:
        class: App\Twig\ObjectProviderExtension
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: twig.extension }

    App\Twig\StringVariableTransformerExtension:
        class: App\Twig\StringVariableTransformerExtension
        arguments: ['@app.transformer.variable']
        tags:
            - { name: twig.extension }

    App\Twig\CountAdvertsProviderExtension:
        class: App\Twig\CountAdvertsProviderExtension
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: twig.extension }