imports:
    - { resource: ./admin_blocks/general.yaml }
    - { resource: ./admin_blocks/user.yaml }
    - { resource: ./admin_blocks/seo.yaml }
    - { resource: ./admin_blocks/city_brand_model_spare_part.yaml }
    - { resource: ./admin_blocks/catalog/city_catalog.yaml }
    - { resource: ./admin_blocks/catalog/brand_catalog.yaml }
    - { resource: ./admin_blocks/catalog/spare_part_catalog.yaml }
    - { resource: ./admin_blocks/catalog/turbo_catalog.yaml }
    - { resource: ./admin_blocks/phone/general.yaml }
    - { resource: ./admin_blocks/user_data.yaml }
    - { resource: ./admin_blocks/error.yaml }
    - { resource: ./admin_blocks/error/obd2_error_catalog.yaml }
    - { resource: ./admin_blocks/universal_page.yaml }

services:
    admin.default_image.default_image:
        class: App\Admin\DefaultImageAdmin
        arguments: [~, App\Entity\DefaultImage, ~, "@app.file_upload", '%upload_image_directory%']
        tags:
            - { name: sonata.admin, group: Каталог изображений, manager_type: orm, label: Каталог изображений, on_top: true}
        public: true

    admin.default_text.default_text:
        class: App\Admin\DefaultTextAdmin
        arguments: [~, App\Entity\DefaultText, ~]
        tags:
            - { name: sonata.admin, group: Каталог текстов, manager_type: orm, label: Каталог текстов, on_top: true}
        public: true