services:
    admin.general.main_page:
        class: App\Admin\MainPageAdmin
        arguments: [~, App\Entity\MainPage, ~]
        tags:
            - { name: sonata.admin, group: Общее, manager_type: orm, label: Главная }
        public: true

    admin.city.city:
        class: App\Admin\CityAdmin
        arguments: [~, App\Entity\City, ~]
        tags:
            - { name: sonata.admin, group: Город, manager_type: orm, label: Город, on_top: true}
        public: true

    admin.brand.brand:
        class: App\Admin\BrandAdmin
        arguments: [~, App\Entity\Brand, 'App\Admin\Controller\BrandAdminController', "@app.file_upload", '%upload_image_directory%', '@router']
        tags:
            - { name: sonata.admin, group: Марка/Модели, manager_type: orm, label: Марка }
        public: true
        calls:
            - [ addChild, ['@admin.brand.models', 'brand']]
            - [ setTemplate, [list, "admin/list_without_pager.html.twig"]]

    admin.brand.models:
        class: App\Admin\ModelAdmin
        arguments: [~, App\Entity\Model, ~, "@app.file_upload", '%upload_image_directory%', '@router', '@doctrine.orm.entity_manager']
        tags:
            - { name: sonata.admin, group: Марка/Модели, manager_type: orm, label: Модель, show_in_dashboard: false }
        public: true
        calls:
            - [ setTemplate, [list, "admin/list_without_pager.html.twig"]]

    admin.catalog.catalog_general:
        class: App\Admin\CatalogGeneralPageAdmin
        arguments: [~, App\Entity\CatalogGeneralPage, ~]
        tags:
            - { name: sonata.admin, group: Каталог от марки, manager_type: orm, label: Выбор марки }
        public: true

    admin.spare_part.spare_part:
        class: App\Admin\SparePartAdmin
        arguments: [~, App\Entity\SparePart, ~, "@app.file_upload", '%upload_image_directory%', '@router']
        tags:
            - { name: sonata.admin, group: Запчасть, manager_type: orm, label: Запчасть, on_top: true, class: "RRRRRRRRR" }
        public: true
        calls:
            - [ setTemplate, [list, "admin/list_without_pager.html.twig"]]