services:
    admin.general.main_page:
        class: App\Admin\MainPageAdmin
        arguments: [~, App\Entity\MainPage, ~]
        tags:
            - { name: sonata.admin, group: Общее, manager_type: orm, label: Главная }
        public: true

    admin.city.city:
        class: App\Admin\CityAdmin
        arguments: [~, App\Entity\City, ~]
        tags:
            - { name: sonata.admin, group: Город, manager_type: orm, label: Город }
        public: true

    admin.brand.brand:
        class: App\Admin\BrandAdmin
        arguments: [~, App\Entity\Brand, ~, "@app.file_upload", '%upload_image_directory%', '@router']
        tags:
            - { name: sonata.admin, group: Марка, manager_type: orm, label: Марка }
        public: true