imports:
    - { resource: ./admin_blocks/general.yaml }
    - { resource: ./admin_blocks/user.yaml }
    - { resource: ./admin_blocks/seo.yaml }
    - { resource: ./admin_blocks/city_brand_model_spare_part.yaml }
    - { resource: ./admin_blocks/city_catalog.yaml }
    - { resource: ./admin_blocks/brand_catalog.yaml }
    - { resource: ./admin_blocks/spare_part_catalog.yaml }
    - { resource: ./admin_blocks/phone/general.yaml }
    - { resource: ./admin_blocks/user_data.yaml }

services:
    admin.add_code.head:
        class: App\Admin\HeadCodeAdmin
        arguments: [~, App\Entity\HeadCode, ~]
        tags:
            - { name: sonata.admin, group: Добавление кода, manager_type: orm, label: В head }
        public: true

    admin.add_code.body:
        class: App\Admin\BodyCodeAdmin
        arguments: [~, App\Entity\BodyCode, ~]
        tags:
            - { name: sonata.admin, group: Добавление кода, manager_type: orm, label: В body }
        public: true

    admin.file.robots_txt:
        class: App\Admin\RobotsTxtAdmin
        arguments: [~, App\Entity\FileChangeTmp, ~, '%robots_txt_file_path%']
        tags:
            - { name: sonata.admin, group: Редактирование файлов, manager_type: orm, label: Редактор robots.txt }
        public: true

    admin.file.site_map_xml:
        class: App\Admin\SiteMapXmlAdmin
        arguments: [~, App\Entity\FileChangeTmp, ~, '%site_map_xml_file_path%']
        tags:
            - { name: sonata.admin, group: Редактирование файлов, manager_type: orm, label: Статический sitemap }
        public: true

    admin.default_image.default_image:
        class: App\Admin\DefaultImageAdmin
        arguments: [~, App\Entity\DefaultImage, ~, "@app.file_upload", '%upload_image_directory%']
        tags:
            - { name: sonata.admin, group: Каталог изображений, manager_type: orm, label: Каталог изображений, on_top: true}
        public: true

    admin.default_text.default_text:
        class: App\Admin\DefaultTextAdmin
        arguments: [~, App\Entity\DefaultText, ~]
        tags:
            - { name: sonata.admin, group: Каталог текстов, manager_type: orm, label: Каталог текстов, on_top: true}
        public: true