services:
    app.form.client_cars_type:
        class: App\Form\Type\ClientCarsType
        arguments: ["@app.provider.form.client_car_provider", "@app.form.transformer.id_to_brand", "@app.form.transformer.id_to_model", "@app.form.transformer.id_to_vehicle_type", "@app.form.transformer.id_to_engine_type"]
        tags:
            - { name: form.type }

    app.form.spare_part_general_advert_type:
        class: App\Form\Type\SparePartGeneralAdvertType
        arguments: ["@app.provider.form.auto_advert_data_provider", "@app.form.transformer.id_to_brand", "@app.form.transformer.ids_to_models", "@app.form.transformer.ids_to_spare_parts"]
        tags:
            - { name: form.type }

    app.form.spare_part_specific_advert_type:
        class: App\Form\Type\SparePartSprecificAdvertType
        arguments:
            "@app.provider.form.spare_part_advert_provider"
            "@app.form.transformer.id_to_brand"
            "@app.form.transformer.id_to_model"
            "@app.form.transformer.id_to_vehicle_type"
            "@app.form.transformer.name_to_spare_part"
            "@app.form.transformer.id_to_drive_type"
            "@app.form.transformer.id_to_gear_box_type"
        tags:
            - { name: form.type }

    app.form.seller_company_type:
        class: App\Form\Type\SellerCompanyType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    app.form.personal_data_type:
        class: App\Form\Type\PersonalDataType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }