security:
    role_hierarchy:
        ROLE_ADMIN_ARTICLE_WRITER:
            - ROLE_ADMIN_ARTICLE_ARTICLE_CREATE
            - ROLE_ADMIN_ARTICLE_ARTICLE_EDIT
            - ROLE_ADMIN_ARTICLE_ARTICLE_LIST

    encoders:
        App\Entity\User: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

        db_multpiple_field_provider:
            id: app.security.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: db_multpiple_field_provider
            switch_user: true
            form_login:
                #provider: fos_userbundle
                #csrf_token_generator: security.csrf.token_manager
                login_path: login
                check_path: login
                username_parameter: _username

            logout:
                path: /logout
                target: /

            remember_me:
                secret:   '%env(APP_SECRET)%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                #always_remember_me: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_ADMIN_ARTICLE_WRITER] }
        # - { path: ^/profile, roles: ROLE_USER }
