sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    assets:
        extra_stylesheets:
            - 'css/admin/general.css'
            - 'css/admin/model.css'
            - 'css/admin/spare-part.css'
        extra_javascripts:
            - 'js/admin/spare-part.js'
            - 'js/admin/article-image.js'
            - 'js/admin/article-image.js'

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
