services:
    admin.user_data.user_engine:
        class: App\Admin\UserData\UserEngineAdmin
        arguments: [~, App\Entity\UserData\UserEngine, ~]
        tags:
            - { name: sonata.admin, group: Данные от пользователей, manager_type: orm, label: Двигатели }
        public: true
    admin.user_data.user_obd2_error_code:
        class: App\Admin\UserData\UserOBD2ErrorCodeAdmin
        arguments: [~, App\Entity\UserData\UserOBD2ErrorCode, ~]
        tags:
            - { name: sonata.admin, group: Данные от пользователей, manager_type: orm, label: Коды OBD2 }
        public: true
    admin.user_data.potential_user_check_fine:
        class: App\Admin\UserData\PotentialUserCheckFineAdmin
        arguments: [~, App\Entity\UserData\PotentialUserCheckFine, ~]
        tags:
            - { name: sonata.admin, group: Данные от пользователей, manager_type: orm, label: Потенциальные пользователи }
        public: true