services:
    admin.user_data.user_engine:
        class: App\Admin\UserData\UserEngineAdmin
        arguments: [~, App\Entity\UserEngine, ~]
        tags:
            - { name: sonata.admin, group: Данные от пользователей, manager_type: orm, label: Двигатели }
        public: true