services:
# 1st from Selling
    admin.phone_catalog.selling.brand:
        class: App\Admin\Phone\Catalog\Selling\CatalogPhoneSellingChoicePhoneBrandAdmin
        arguments: [~, App\Entity\Phone\Catalog\Selling\CatalogPhoneSellingChoicePhoneBrand, ~]
        tags:
            - { name: sonata.admin, group: Каталог продажи Тел, manager_type: orm, label: Выбор марки Тел }
        public: true

# 2nd from Selling
    admin.phone_catalog.selling.model:
        class: App\Admin\Phone\Catalog\Selling\CatalogPhoneSellingChoicePhoneModelAdmin
        arguments: [~, App\Entity\Phone\Catalog\Selling\CatalogPhoneSellingChoicePhoneModel, ~]
        tags:
            - { name: sonata.admin, group: Каталог продажи Тел, manager_type: orm, label: Выбор модели Тел }
        public: true

# 3rd from Selling
    admin.phone_catalog.selling.city:
        class: App\Admin\Phone\Catalog\Selling\CatalogPhoneSellingChoiceCityAdmin
        arguments: [~, App\Entity\Phone\Catalog\Selling\CatalogPhoneSellingChoiceCity, ~]
        tags:
            - { name: sonata.admin, group: Каталог продажи Тел, manager_type: orm, label: Выбор города Тел }
        public: true

# 4th from Selling
    admin.phone_catalog.selling.final_page:
        class: App\Admin\Phone\Catalog\Selling\CatalogPhoneSellingFinalPageAdmin
        arguments: [~, App\Entity\Phone\Catalog\Selling\CatalogPhoneSellingFinalPage, ~]
        tags:
            - { name: sonata.admin, group: Каталог продажи Тел, manager_type: orm, label: Финальная страница }
        public: true