monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            #path:  "php://stderr"
            level: debug
        console:
            type:  console
        rollbar:
            type: service
            id: Rollbar\Monolog\Handler\RollbarHandler
#        main:
#            type: fingers_crossed
#            action_level: error
#            handler: nested
#            excluded_404s:
#                # regex: exclude all 404 errors from the logs
#                - ^/
#        nested:
#            type: stream
#            path: "%kernel.logs_dir%/%kernel.environment%.log"
#            level: debug
#        console:
#            type: console
#            process_psr_3_messages: false
#            channels: ["!event", "!doctrine"]
#        deprecation:
#            type: stream
#            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
#        deprecation_filter:
#            type: filter
#            handler: deprecation
#            max_level: info
#            channels: ["php"]
